In [1]:
import pandas as pd
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [2]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [3]:
independant=dataset[["age","bmi","children","sex_male","smoker_yes"]]
dependant=dataset[["charges"]]

In [4]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(independant,dependant,test_size=0.30,random_state=0)

In [5]:
from sklearn.preprocessing import StandardScaler
std=StandardScaler()
X_train=std.fit_transform(X_train)
X_test=std.transform(X_test)

In [7]:
pip install catboost

Collecting catboost
  Downloading catboost-1.2.8-cp313-cp313-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Downloading graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\users\ragap\anaconda3\lib\site-packages (from catboost) (3.10.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\users\ragap\anaconda3\lib\site-packages (from catboost) (2.1.3)
Requirement already satisfied: pandas>=0.24 in c:\users\ragap\anaconda3\lib\site-packages (from catboost) (2.2.3)
Requirement already satisfied: scipy in c:\users\ragap\anaconda3\lib\site-packages (from catboost) (1.15.3)
Requirement already satisfied: plotly in c:\users\ragap\anaconda3\lib\site-packages (from catboost) (5.24.1)
Requirement already satisfied: six in c:\users\ragap\anaconda3\lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ragap\anaconda3\lib\site-packages (from pandas>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ragap\anaconda3\lib\site-packages (from pandas>=0.24->catboost) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ragap\anaconda3\lib\site-packages (from pandas>=0.24->catboost) (2025.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\ragap\anaconda3\lib\site-packages (from matplotlib->catboost) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\ragap\anaconda3\lib\site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\ragap\anaconda3\lib\site-packages (from matplotlib->catboost) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\ragap\anaconda3\lib\site-packages (from matplotlib->catboost) (1.4.8)
Requirement already satisfied: packaging>=20.0 in c:\users\ragap\anaconda3\lib\site-packages (from matplotlib->catboost) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\ragap\anaconda3\lib\site-packages (from matplotlib->catboost) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\ragap\anaconda3\lib\site-packages (from matplotlib->catboost) (3.2.0)
Requirement already satisfied: tenacity>=6.2.0 in c:\users\ragap\anaconda3\lib\site-packages (from plotly->catboost) (9.0.0)
Downloading catboost-1.2.8-cp313-cp313-win_amd64.whl (102.4 MB)
   ---------------------------------------- 0.0/102.4 MB ? eta -:--:--
    --------------------------------------- 2.1/102.4 MB 10.6 MB/s eta 0:00:10
   - -------------------------------------- 4.5/102.4 MB 10.9 MB/s eta 0:00:09
   -- ------------------------------------- 6.6/102.4 MB 10.9 MB/s eta 0:00:09
   --- ------------------------------------ 8.9/102.4 MB 10.9 MB/s eta 0:00:09
   ---- ----------------------------------- 11.0/102.4 MB 10.8 MB/s eta 0:00:09
   ----- ---------------------------------- 13.1/102.4 MB 10.8 MB/s eta 0:00:09
   ------ --------------------------------- 15.5/102.4 MB 10.8 MB/s eta 0:00:09
   ------ --------------------------------- 17.8/102.4 MB 10.8 MB/s eta 0:00:08
   ------- -------------------------------- 19.9/102.4 MB 10.8 MB/s eta 0:00:08
   -------- ------------------------------- 22.0/102.4 MB 10.8 MB/s eta 0:00:08
   --------- ------------------------------ 24.4/102.4 MB 10.8 MB/s eta 0:00:08
   ---------- ----------------------------- 26.7/102.4 MB 10.8 MB/s eta 0:00:08
   ----------- ---------------------------- 28.8/102.4 MB 10.8 MB/s eta 0:00:07
   ------------ --------------------------- 30.9/102.4 MB 10.8 MB/s eta 0:00:07
   ------------- -------------------------- 33.3/102.4 MB 10.8 MB/s eta 0:00:07
   ------------- -------------------------- 35.7/102.4 MB 10.8 MB/s eta 0:00:07
   -------------- ------------------------- 37.7/102.4 MB 10.8 MB/s eta 0:00:06
   --------------- ------------------------ 40.1/102.4 MB 10.8 MB/s eta 0:00:06
   ---------------- ----------------------- 42.2/102.4 MB 10.8 MB/s eta 0:00:06
   ----------------- ---------------------- 44.6/102.4 MB 10.8 MB/s eta 0:00:06
   ------------------ --------------------- 46.7/102.4 MB 10.8 MB/s eta 0:00:06
   ------------------- -------------------- 48.8/102.4 MB 10.8 MB/s eta 0:00:05
   ------------------- -------------------- 51.1/102.4 MB 10.8 MB/s eta 0:00:05
   -------------------- ------------------- 53.2/102.4 MB 10.8 MB/s eta 0:00:05
   --------------------- ------------------ 55.3/102.4 MB 10.8 MB/s eta 0:00:05
   ---------------------- ----------------- 57.7/102.4 MB 10.8 MB/s eta 0:00:05
   ----------------------- ---------------- 60.0/102.4 MB 10.8 MB/s eta 0:00:04
   ------------------------ --------------- 62.4/102.4 MB 10.8 MB/s eta 0:00:04
   ------------------------- -------------- 64.5/102.4 MB 10.8 MB/s eta 0:00:04
   -------------------------- ------------- 66.8/102.4 MB 10.8 MB/s eta 0:00:04
   -------------------------- ------------- 67.9/102.4 MB 10.6 MB/s eta 0:00:04
   -------------------------- ------------- 68.4/102.4 MB 10.3 MB/s eta 0:00:04
   --------------------------- ------------ 69.5/102.4 MB 10.2 MB/s eta 0:00:04
   --------------------------- ------------ 71.3/102.4 MB 10.1 MB/s eta 0:00:04
   ---------------------------- ----------- 73.4/102.4 MB 10.2 MB/s eta 0:00:03
   ----------------------------- ---------- 76.0/102.4 MB 10.2 MB/s eta 0:00:03
   ------------------------------ --------- 78.1/102.4 MB 10.2 MB/s eta 0:00:03
   ------------------------------- -------- 80.2/102.4 MB 10.2 MB/s eta 0:00:03
   -------------------------------- ------- 82.6/102.4 MB 10.2 MB/s eta 0:00:02
   --------------------------------- ------ 84.7/102.4 MB 10.3 MB/s eta 0:00:02
   --------------------------------- ------ 87.0/102.4 MB 10.3 MB/s eta 0:00:02
   ---------------------------------- ----- 89.1/102.4 MB 10.3 MB/s eta 0:00:02
   ----------------------------------- ---- 91.2/102.4 MB 10.3 MB/s eta 0:00:02
   ------------------------------------ --- 93.6/102.4 MB 10.3 MB/s eta 0:00:01
   ------------------------------------- -- 95.9/102.4 MB 10.3 MB/s eta 0:00:01
   -------------------------------------- - 98.3/102.4 MB 10.3 MB/s eta 0:00:01
   --------------------------------------  100.4/102.4 MB 10.3 MB/s eta 0:00:01
   --------------------------------------  102.2/102.4 MB 10.3 MB/s eta 0:00:01
   --------------------------------------- 102.4/102.4 MB 10.2 MB/s eta 0:00:00
Downloading graphviz-0.21-py3-none-any.whl (47 kB)
Installing collected packages: graphviz, catboost

   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   -------------------- ------------------- 1/2 [catboost]
   ---------------------------------------- 2/2 [catboost]

Successfully installed catboost-1.2.8 graphviz-0.21
Note: you may need to restart the kernel to use updated packages.

In [8]:
from catboost import CatBoostRegressor
model=CatBoostRegressor()
model.fit(X_train,Y_train)

Learning rate set to 0.040517
0:	learn: 11523.9646319	total: 124ms	remaining: 2m 3s
1:	learn: 11187.5035759	total: 125ms	remaining: 1m 2s
2:	learn: 10883.1216711	total: 126ms	remaining: 41.8s
3:	learn: 10577.5235903	total: 126ms	remaining: 31.4s
4:	learn: 10309.6159300	total: 127ms	remaining: 25.3s
5:	learn: 10045.7339176	total: 128ms	remaining: 21.2s
6:	learn: 9796.7131391	total: 129ms	remaining: 18.2s
7:	learn: 9545.5591085	total: 129ms	remaining: 16s
8:	learn: 9309.0455223	total: 130ms	remaining: 14.3s
9:	learn: 9068.0175507	total: 131ms	remaining: 12.9s
10:	learn: 8825.3924183	total: 131ms	remaining: 11.8s
11:	learn: 8609.7982621	total: 132ms	remaining: 10.9s
12:	learn: 8417.2780903	total: 133ms	remaining: 10.1s
13:	learn: 8226.1317607	total: 133ms	remaining: 9.4s
14:	learn: 8026.2365118	total: 134ms	remaining: 8.79s
15:	learn: 7864.3770346	total: 135ms	remaining: 8.28s
16:	learn: 7679.1288616	total: 135ms	remaining: 7.83s
17:	learn: 7514.1189113	total: 136ms	remaining: 7.43s
18:	learn: 7361.8757259	total: 137ms	remaining: 7.05s
19:	learn: 7217.9978687	total: 137ms	remaining: 6.73s
20:	learn: 7079.2985280	total: 138ms	remaining: 6.42s
21:	learn: 6951.2874677	total: 138ms	remaining: 6.15s
22:	learn: 6820.3709841	total: 139ms	remaining: 5.91s
23:	learn: 6692.3141619	total: 140ms	remaining: 5.69s
24:	learn: 6578.1407940	total: 141ms	remaining: 5.49s
25:	learn: 6467.7579640	total: 141ms	remaining: 5.3s
26:	learn: 6352.1898666	total: 142ms	remaining: 5.13s
27:	learn: 6259.5847303	total: 143ms	remaining: 4.97s
28:	learn: 6166.7287565	total: 144ms	remaining: 4.82s
29:	learn: 6083.7126563	total: 144ms	remaining: 4.67s
30:	learn: 6020.4132262	total: 145ms	remaining: 4.52s
31:	learn: 5947.6102519	total: 145ms	remaining: 4.39s
32:	learn: 5869.5771561	total: 146ms	remaining: 4.28s
33:	learn: 5784.8697366	total: 147ms	remaining: 4.17s
34:	learn: 5715.8093402	total: 148ms	remaining: 4.07s
35:	learn: 5654.4568573	total: 148ms	remaining: 3.97s
36:	learn: 5585.5997171	total: 149ms	remaining: 3.88s
37:	learn: 5535.0197124	total: 150ms	remaining: 3.79s
38:	learn: 5476.0177851	total: 150ms	remaining: 3.7s
39:	learn: 5419.2151344	total: 151ms	remaining: 3.62s
40:	learn: 5364.7367245	total: 152ms	remaining: 3.55s
41:	learn: 5315.2664355	total: 153ms	remaining: 3.48s
42:	learn: 5269.3220236	total: 153ms	remaining: 3.42s
43:	learn: 5221.7860042	total: 154ms	remaining: 3.35s
44:	learn: 5177.9655767	total: 155ms	remaining: 3.29s
45:	learn: 5139.5191385	total: 156ms	remaining: 3.24s
46:	learn: 5100.5552635	total: 157ms	remaining: 3.18s
47:	learn: 5065.6493553	total: 158ms	remaining: 3.13s
48:	learn: 5030.9363623	total: 159ms	remaining: 3.08s
49:	learn: 4997.6547197	total: 160ms	remaining: 3.03s
50:	learn: 4967.5085894	total: 160ms	remaining: 2.99s
51:	learn: 4938.7512900	total: 161ms	remaining: 2.94s
52:	learn: 4910.0911316	total: 162ms	remaining: 2.9s
53:	learn: 4882.5748786	total: 163ms	remaining: 2.86s
54:	learn: 4858.2138869	total: 164ms	remaining: 2.82s
55:	learn: 4834.3485744	total: 165ms	remaining: 2.78s
56:	learn: 4809.8150278	total: 166ms	remaining: 2.74s
57:	learn: 4789.0047862	total: 167ms	remaining: 2.71s
58:	learn: 4768.3064342	total: 167ms	remaining: 2.67s
59:	learn: 4749.0350041	total: 168ms	remaining: 2.64s
60:	learn: 4732.1281459	total: 169ms	remaining: 2.6s
61:	learn: 4712.4775849	total: 170ms	remaining: 2.57s
62:	learn: 4695.7514258	total: 171ms	remaining: 2.54s
63:	learn: 4677.9528742	total: 172ms	remaining: 2.51s
64:	learn: 4663.4980275	total: 173ms	remaining: 2.48s
65:	learn: 4649.5902909	total: 174ms	remaining: 2.46s
66:	learn: 4632.5406025	total: 174ms	remaining: 2.43s
67:	learn: 4618.4604303	total: 175ms	remaining: 2.4s
68:	learn: 4605.6566002	total: 176ms	remaining: 2.38s
69:	learn: 4593.5637387	total: 177ms	remaining: 2.35s
70:	learn: 4581.2189223	total: 178ms	remaining: 2.33s
71:	learn: 4568.7413697	total: 179ms	remaining: 2.3s
72:	learn: 4558.0935953	total: 180ms	remaining: 2.28s
73:	learn: 4549.7515640	total: 180ms	remaining: 2.26s
74:	learn: 4543.1303256	total: 181ms	remaining: 2.23s
75:	learn: 4532.8482821	total: 182ms	remaining: 2.21s
76:	learn: 4523.5998973	total: 183ms	remaining: 2.19s
77:	learn: 4514.7194228	total: 183ms	remaining: 2.17s
78:	learn: 4504.6053834	total: 184ms	remaining: 2.15s
79:	learn: 4495.7434837	total: 185ms	remaining: 2.13s
80:	learn: 4488.1452898	total: 186ms	remaining: 2.11s
81:	learn: 4480.3839154	total: 187ms	remaining: 2.09s
82:	learn: 4471.6396860	total: 188ms	remaining: 2.07s
83:	learn: 4465.0373791	total: 189ms	remaining: 2.06s
84:	learn: 4461.3737880	total: 189ms	remaining: 2.04s
85:	learn: 4454.4992323	total: 190ms	remaining: 2.02s
86:	learn: 4448.8786864	total: 191ms	remaining: 2.01s
87:	learn: 4443.6445263	total: 192ms	remaining: 1.99s
88:	learn: 4437.6620564	total: 193ms	remaining: 1.98s
89:	learn: 4428.8136571	total: 194ms	remaining: 1.96s
90:	learn: 4423.3560551	total: 195ms	remaining: 1.94s
91:	learn: 4418.4143395	total: 195ms	remaining: 1.93s
92:	learn: 4410.9546570	total: 196ms	remaining: 1.92s
93:	learn: 4406.4984226	total: 197ms	remaining: 1.9s
94:	learn: 4400.0530981	total: 198ms	remaining: 1.89s
95:	learn: 4395.3203724	total: 199ms	remaining: 1.87s
96:	learn: 4389.9311458	total: 200ms	remaining: 1.86s
97:	learn: 4385.6640405	total: 201ms	remaining: 1.85s
98:	learn: 4379.8287159	total: 202ms	remaining: 1.83s
99:	learn: 4375.7922939	total: 203ms	remaining: 1.83s
100:	learn: 4372.9414479	total: 204ms	remaining: 1.81s
101:	learn: 4369.4032699	total: 205ms	remaining: 1.8s
102:	learn: 4364.0127662	total: 206ms	remaining: 1.79s
103:	learn: 4358.9958548	total: 206ms	remaining: 1.78s
104:	learn: 4357.1049417	total: 207ms	remaining: 1.76s
105:	learn: 4355.3808200	total: 208ms	remaining: 1.75s
106:	learn: 4353.9652889	total: 208ms	remaining: 1.74s
107:	learn: 4352.4364287	total: 209ms	remaining: 1.73s
108:	learn: 4348.6321118	total: 210ms	remaining: 1.72s
109:	learn: 4345.4980505	total: 211ms	remaining: 1.7s
110:	learn: 4342.4044423	total: 211ms	remaining: 1.69s
111:	learn: 4340.3014078	total: 212ms	remaining: 1.68s
112:	learn: 4334.8317979	total: 213ms	remaining: 1.67s
113:	learn: 4331.4067137	total: 214ms	remaining: 1.66s
114:	learn: 4328.1886720	total: 214ms	remaining: 1.65s
115:	learn: 4324.9642275	total: 215ms	remaining: 1.64s
116:	learn: 4322.4596167	total: 216ms	remaining: 1.63s
117:	learn: 4320.4090982	total: 217ms	remaining: 1.62s
118:	learn: 4317.8379222	total: 218ms	remaining: 1.61s
119:	learn: 4314.6203902	total: 219ms	remaining: 1.6s
120:	learn: 4309.9900305	total: 219ms	remaining: 1.59s
121:	learn: 4307.9217560	total: 220ms	remaining: 1.58s
122:	learn: 4305.4028129	total: 221ms	remaining: 1.58s
123:	learn: 4303.6776330	total: 222ms	remaining: 1.57s
124:	learn: 4300.5584023	total: 223ms	remaining: 1.56s
125:	learn: 4297.0096207	total: 224ms	remaining: 1.55s
126:	learn: 4292.9004106	total: 225ms	remaining: 1.54s
127:	learn: 4288.1472697	total: 226ms	remaining: 1.54s
128:	learn: 4284.0117053	total: 226ms	remaining: 1.53s
129:	learn: 4280.1065466	total: 227ms	remaining: 1.52s
130:	learn: 4276.4782732	total: 228ms	remaining: 1.51s
131:	learn: 4272.7185659	total: 229ms	remaining: 1.51s
132:	learn: 4270.6252825	total: 230ms	remaining: 1.5s
133:	learn: 4268.7834190	total: 231ms	remaining: 1.49s
134:	learn: 4265.9873091	total: 232ms	remaining: 1.48s
135:	learn: 4262.9065124	total: 233ms	remaining: 1.48s
136:	learn: 4259.9568765	total: 234ms	remaining: 1.47s
137:	learn: 4257.7081296	total: 234ms	remaining: 1.46s
138:	learn: 4255.3123675	total: 235ms	remaining: 1.46s
139:	learn: 4251.7142862	total: 236ms	remaining: 1.45s
140:	learn: 4246.0893453	total: 237ms	remaining: 1.44s
141:	learn: 4242.9419926	total: 238ms	remaining: 1.44s
142:	learn: 4240.4810671	total: 239ms	remaining: 1.43s
143:	learn: 4236.2879747	total: 240ms	remaining: 1.43s
144:	learn: 4233.7308890	total: 241ms	remaining: 1.42s
145:	learn: 4229.3151363	total: 242ms	remaining: 1.41s
146:	learn: 4226.7913552	total: 242ms	remaining: 1.41s
147:	learn: 4224.4266717	total: 243ms	remaining: 1.4s
148:	learn: 4220.7263346	total: 244ms	remaining: 1.39s
149:	learn: 4218.7415301	total: 245ms	remaining: 1.39s
150:	learn: 4215.7041868	total: 246ms	remaining: 1.38s
151:	learn: 4214.0456029	total: 247ms	remaining: 1.38s
152:	learn: 4212.2385164	total: 247ms	remaining: 1.37s
153:	learn: 4208.3484656	total: 248ms	remaining: 1.36s
154:	learn: 4205.7395178	total: 249ms	remaining: 1.36s
155:	learn: 4203.4005741	total: 250ms	remaining: 1.35s
156:	learn: 4202.3976365	total: 251ms	remaining: 1.34s
157:	learn: 4201.0630429	total: 252ms	remaining: 1.34s
158:	learn: 4199.6578544	total: 252ms	remaining: 1.33s
159:	learn: 4193.8431122	total: 253ms	remaining: 1.33s
160:	learn: 4190.6127946	total: 254ms	remaining: 1.32s
161:	learn: 4188.9113228	total: 255ms	remaining: 1.32s
162:	learn: 4186.7534594	total: 256ms	remaining: 1.31s
163:	learn: 4185.2423695	total: 257ms	remaining: 1.31s
164:	learn: 4181.8051172	total: 258ms	remaining: 1.3s
165:	learn: 4175.4674443	total: 258ms	remaining: 1.3s
166:	learn: 4174.1730221	total: 259ms	remaining: 1.29s
167:	learn: 4172.4785186	total: 260ms	remaining: 1.29s
168:	learn: 4170.1000659	total: 261ms	remaining: 1.28s
169:	learn: 4165.8373140	total: 262ms	remaining: 1.28s
170:	learn: 4161.0913560	total: 263ms	remaining: 1.27s
171:	learn: 4159.7735419	total: 264ms	remaining: 1.27s
172:	learn: 4158.6291524	total: 264ms	remaining: 1.26s
173:	learn: 4156.2263715	total: 265ms	remaining: 1.26s
174:	learn: 4154.6221503	total: 266ms	remaining: 1.25s
175:	learn: 4152.5151652	total: 267ms	remaining: 1.25s
176:	learn: 4150.4199058	total: 268ms	remaining: 1.25s
177:	learn: 4147.2871496	total: 269ms	remaining: 1.24s
178:	learn: 4146.2391820	total: 270ms	remaining: 1.24s
179:	learn: 4145.7699317	total: 270ms	remaining: 1.23s
180:	learn: 4144.2396490	total: 271ms	remaining: 1.23s
181:	learn: 4137.7543255	total: 272ms	remaining: 1.22s
182:	learn: 4135.5508063	total: 273ms	remaining: 1.22s
183:	learn: 4131.4809468	total: 274ms	remaining: 1.21s
184:	learn: 4127.9773403	total: 274ms	remaining: 1.21s
185:	learn: 4126.2053856	total: 275ms	remaining: 1.2s
186:	learn: 4123.7102826	total: 276ms	remaining: 1.2s
187:	learn: 4122.1317394	total: 277ms	remaining: 1.2s
188:	learn: 4116.8643009	total: 278ms	remaining: 1.19s
189:	learn: 4115.6357668	total: 279ms	remaining: 1.19s
190:	learn: 4114.4120188	total: 280ms	remaining: 1.18s
191:	learn: 4111.3595778	total: 280ms	remaining: 1.18s
192:	learn: 4109.4632453	total: 281ms	remaining: 1.18s
193:	learn: 4105.4000351	total: 282ms	remaining: 1.17s
194:	learn: 4104.3185914	total: 283ms	remaining: 1.17s
195:	learn: 4101.3002442	total: 284ms	remaining: 1.17s
196:	learn: 4099.3023181	total: 285ms	remaining: 1.16s
197:	learn: 4098.2656512	total: 286ms	remaining: 1.16s
198:	learn: 4096.9078997	total: 287ms	remaining: 1.15s
199:	learn: 4095.7023786	total: 288ms	remaining: 1.15s
200:	learn: 4093.6101452	total: 289ms	remaining: 1.15s
201:	learn: 4090.6554631	total: 289ms	remaining: 1.14s
202:	learn: 4088.8990239	total: 290ms	remaining: 1.14s
203:	learn: 4085.9511286	total: 291ms	remaining: 1.14s
204:	learn: 4085.7219031	total: 292ms	remaining: 1.13s
205:	learn: 4083.2624985	total: 292ms	remaining: 1.13s
206:	learn: 4081.4758088	total: 293ms	remaining: 1.12s
207:	learn: 4079.2393979	total: 294ms	remaining: 1.12s
208:	learn: 4076.3391765	total: 295ms	remaining: 1.11s
209:	learn: 4075.6513910	total: 296ms	remaining: 1.11s
210:	learn: 4074.9077532	total: 296ms	remaining: 1.11s
211:	learn: 4071.6380809	total: 297ms	remaining: 1.1s
212:	learn: 4070.3723273	total: 298ms	remaining: 1.1s
213:	learn: 4069.8151432	total: 299ms	remaining: 1.1s
214:	learn: 4067.8901853	total: 299ms	remaining: 1.09s
215:	learn: 4067.1544681	total: 300ms	remaining: 1.09s
216:	learn: 4066.0981802	total: 301ms	remaining: 1.08s
217:	learn: 4065.1416906	total: 302ms	remaining: 1.08s
218:	learn: 4063.6564706	total: 303ms	remaining: 1.08s
219:	learn: 4061.3364446	total: 303ms	remaining: 1.07s
220:	learn: 4057.0896912	total: 304ms	remaining: 1.07s
221:	learn: 4055.0450651	total: 305ms	remaining: 1.07s
222:	learn: 4053.4590442	total: 306ms	remaining: 1.06s
223:	learn: 4052.5192462	total: 307ms	remaining: 1.06s
224:	learn: 4051.3215994	total: 308ms	remaining: 1.06s
225:	learn: 4047.6380022	total: 308ms	remaining: 1.06s
226:	learn: 4046.6061243	total: 309ms	remaining: 1.05s
227:	learn: 4045.5268490	total: 310ms	remaining: 1.05s
228:	learn: 4040.5289797	total: 311ms	remaining: 1.05s
229:	learn: 4038.0090118	total: 312ms	remaining: 1.04s
230:	learn: 4032.0433785	total: 313ms	remaining: 1.04s
231:	learn: 4028.2111169	total: 313ms	remaining: 1.04s
232:	learn: 4025.4358893	total: 314ms	remaining: 1.03s
233:	learn: 4023.2531612	total: 315ms	remaining: 1.03s
234:	learn: 4020.1447661	total: 316ms	remaining: 1.03s
235:	learn: 4018.1525656	total: 317ms	remaining: 1.02s
236:	learn: 4017.3237863	total: 318ms	remaining: 1.02s
237:	learn: 4015.6192771	total: 318ms	remaining: 1.02s
238:	learn: 4014.5519637	total: 319ms	remaining: 1.02s
239:	learn: 4013.6040548	total: 320ms	remaining: 1.01s
240:	learn: 4012.8068204	total: 321ms	remaining: 1.01s
241:	learn: 4011.4300676	total: 322ms	remaining: 1.01s
242:	learn: 4008.4027295	total: 322ms	remaining: 1s
243:	learn: 4007.3974047	total: 323ms	remaining: 1s
244:	learn: 4006.6412909	total: 324ms	remaining: 999ms
245:	learn: 4005.2470371	total: 325ms	remaining: 996ms
246:	learn: 4002.3011781	total: 326ms	remaining: 993ms
247:	learn: 4001.6942704	total: 327ms	remaining: 991ms
248:	learn: 3999.2496321	total: 328ms	remaining: 988ms
249:	learn: 3998.6012617	total: 328ms	remaining: 985ms
250:	learn: 3996.9387062	total: 329ms	remaining: 983ms
251:	learn: 3994.0325988	total: 330ms	remaining: 980ms
252:	learn: 3993.2479323	total: 331ms	remaining: 977ms
253:	learn: 3991.1312336	total: 332ms	remaining: 975ms
254:	learn: 3987.8394153	total: 333ms	remaining: 972ms
255:	learn: 3987.1247960	total: 333ms	remaining: 969ms
256:	learn: 3984.8601291	total: 334ms	remaining: 967ms
257:	learn: 3984.1471690	total: 335ms	remaining: 964ms
258:	learn: 3983.4047701	total: 336ms	remaining: 961ms
259:	learn: 3982.7378529	total: 337ms	remaining: 958ms
260:	learn: 3982.1436114	total: 338ms	remaining: 956ms
261:	learn: 3981.5264727	total: 338ms	remaining: 953ms
262:	learn: 3980.1715082	total: 339ms	remaining: 951ms
263:	learn: 3979.5348296	total: 340ms	remaining: 948ms
264:	learn: 3978.9350518	total: 341ms	remaining: 946ms
265:	learn: 3973.5886079	total: 342ms	remaining: 943ms
266:	learn: 3972.8996610	total: 343ms	remaining: 941ms
267:	learn: 3966.8386065	total: 344ms	remaining: 939ms
268:	learn: 3966.2117177	total: 345ms	remaining: 936ms
269:	learn: 3965.5609797	total: 346ms	remaining: 934ms
270:	learn: 3962.2983946	total: 346ms	remaining: 932ms
271:	learn: 3961.6217040	total: 347ms	remaining: 929ms
272:	learn: 3960.1491023	total: 348ms	remaining: 927ms
273:	learn: 3958.1364714	total: 349ms	remaining: 925ms
274:	learn: 3957.5147722	total: 350ms	remaining: 923ms
275:	learn: 3952.5974418	total: 351ms	remaining: 921ms
276:	learn: 3951.7829744	total: 352ms	remaining: 918ms
277:	learn: 3951.2076079	total: 353ms	remaining: 916ms
278:	learn: 3948.9133544	total: 354ms	remaining: 914ms
279:	learn: 3947.3464329	total: 355ms	remaining: 912ms
280:	learn: 3946.5386974	total: 355ms	remaining: 909ms
281:	learn: 3945.9779271	total: 356ms	remaining: 907ms
282:	learn: 3945.4300948	total: 357ms	remaining: 905ms
283:	learn: 3944.7985910	total: 358ms	remaining: 902ms
284:	learn: 3943.3357528	total: 359ms	remaining: 900ms
285:	learn: 3942.8201301	total: 360ms	remaining: 898ms
286:	learn: 3942.2984768	total: 360ms	remaining: 895ms
287:	learn: 3937.1539289	total: 361ms	remaining: 893ms
288:	learn: 3936.6603406	total: 362ms	remaining: 890ms
289:	learn: 3932.8616332	total: 363ms	remaining: 888ms
290:	learn: 3930.6525055	total: 364ms	remaining: 886ms
291:	learn: 3930.0460422	total: 364ms	remaining: 884ms
292:	learn: 3929.5404634	total: 365ms	remaining: 881ms
293:	learn: 3928.6955646	total: 366ms	remaining: 879ms
294:	learn: 3927.8344753	total: 367ms	remaining: 877ms
295:	learn: 3927.4012595	total: 368ms	remaining: 874ms
296:	learn: 3926.7798952	total: 368ms	remaining: 872ms
297:	learn: 3925.2556324	total: 369ms	remaining: 870ms
298:	learn: 3924.8409781	total: 370ms	remaining: 868ms
299:	learn: 3922.7625703	total: 371ms	remaining: 865ms
300:	learn: 3921.6027483	total: 372ms	remaining: 863ms
301:	learn: 3921.1005263	total: 373ms	remaining: 861ms
302:	learn: 3920.6671089	total: 373ms	remaining: 859ms
303:	learn: 3915.8590831	total: 374ms	remaining: 857ms
304:	learn: 3914.6807542	total: 375ms	remaining: 854ms
305:	learn: 3910.5180457	total: 376ms	remaining: 852ms
306:	learn: 3908.8699263	total: 377ms	remaining: 850ms
307:	learn: 3907.3573813	total: 377ms	remaining: 848ms
308:	learn: 3905.4132862	total: 378ms	remaining: 846ms
309:	learn: 3902.0018406	total: 380ms	remaining: 845ms
310:	learn: 3900.9247020	total: 381ms	remaining: 843ms
311:	learn: 3899.1512808	total: 381ms	remaining: 841ms
312:	learn: 3898.7420376	total: 383ms	remaining: 841ms
313:	learn: 3896.9684000	total: 384ms	remaining: 839ms
314:	learn: 3894.3278591	total: 385ms	remaining: 837ms
315:	learn: 3890.9922445	total: 386ms	remaining: 835ms
316:	learn: 3887.8177346	total: 386ms	remaining: 833ms
317:	learn: 3886.2002089	total: 387ms	remaining: 831ms
318:	learn: 3883.5192041	total: 388ms	remaining: 829ms
319:	learn: 3880.9288754	total: 389ms	remaining: 827ms
320:	learn: 3877.0915738	total: 390ms	remaining: 825ms
321:	learn: 3876.7394792	total: 391ms	remaining: 823ms
322:	learn: 3873.2487771	total: 392ms	remaining: 821ms
323:	learn: 3872.2728242	total: 393ms	remaining: 819ms
324:	learn: 3871.5667173	total: 393ms	remaining: 817ms
325:	learn: 3868.5052758	total: 394ms	remaining: 815ms
326:	learn: 3865.5738054	total: 395ms	remaining: 813ms
327:	learn: 3859.9274489	total: 396ms	remaining: 811ms
328:	learn: 3858.7649688	total: 397ms	remaining: 809ms
329:	learn: 3857.2964167	total: 398ms	remaining: 808ms
330:	learn: 3855.3309838	total: 399ms	remaining: 806ms
331:	learn: 3852.7601089	total: 400ms	remaining: 804ms
332:	learn: 3851.5452662	total: 401ms	remaining: 803ms
333:	learn: 3850.9041236	total: 402ms	remaining: 802ms
334:	learn: 3849.6068411	total: 403ms	remaining: 801ms
335:	learn: 3848.6794891	total: 407ms	remaining: 804ms
336:	learn: 3846.4912539	total: 409ms	remaining: 805ms
337:	learn: 3843.5382956	total: 410ms	remaining: 804ms
338:	learn: 3838.1162686	total: 411ms	remaining: 802ms
339:	learn: 3836.1174542	total: 412ms	remaining: 800ms
340:	learn: 3832.7243806	total: 414ms	remaining: 799ms
341:	learn: 3829.9048778	total: 418ms	remaining: 803ms
342:	learn: 3825.6889042	total: 419ms	remaining: 802ms
343:	learn: 3823.8601778	total: 420ms	remaining: 800ms
344:	learn: 3820.3840872	total: 421ms	remaining: 798ms
345:	learn: 3817.1930853	total: 422ms	remaining: 797ms
346:	learn: 3815.5779593	total: 422ms	remaining: 795ms
347:	learn: 3814.0973805	total: 423ms	remaining: 793ms
348:	learn: 3811.7801234	total: 424ms	remaining: 791ms
349:	learn: 3810.0860764	total: 425ms	remaining: 789ms
350:	learn: 3806.7771312	total: 426ms	remaining: 788ms
351:	learn: 3805.4132184	total: 427ms	remaining: 786ms
352:	learn: 3804.0897917	total: 428ms	remaining: 784ms
353:	learn: 3797.7942254	total: 429ms	remaining: 782ms
354:	learn: 3794.3832904	total: 429ms	remaining: 780ms
355:	learn: 3793.1306525	total: 430ms	remaining: 778ms
356:	learn: 3792.4745220	total: 431ms	remaining: 777ms
357:	learn: 3792.1507402	total: 432ms	remaining: 775ms
358:	learn: 3789.9016014	total: 433ms	remaining: 773ms
359:	learn: 3788.2789495	total: 434ms	remaining: 772ms
360:	learn: 3783.4669781	total: 435ms	remaining: 770ms
361:	learn: 3782.7990865	total: 436ms	remaining: 768ms
362:	learn: 3780.7115812	total: 437ms	remaining: 767ms
363:	learn: 3779.6101410	total: 438ms	remaining: 765ms
364:	learn: 3779.1207041	total: 439ms	remaining: 763ms

In [10]:
Y_pred=model.predict(X_test)

In [11]:
from sklearn.metrics import r2_score
r_score=r2_score(Y_test,Y_pred)
r_score

0.8781385891896959